export const runtime = 'edge';

import { Resend } from 'resend';
import { NextResponse } from 'next/server';

const resend = new Resend(process.env.RESEND_API_KEY || 're_placeholder');

export async function POST(request) {
  if (!process.env.RESEND_API_KEY || process.env.RESEND_API_KEY === 're_placeholder') {
    return NextResponse.json({ error: "Server configuration error" }, { status: 500 });
  }

  try {
    const { name, email, phone, service, date, message } = await request.json();

    // Resend'de doğruladığın ana domain adresi
    const verifiedFrom = 'Azime Beauty <info@azimebeauty.com>';

    // TÜM BİLGİLERİ AZİME HANIM'IN MAİLİNE GÖNDERİYORUZ
    await resend.emails.send({
      from: verifiedFrom, 
      to: 'azimebeauty@gmail.com', // Bilgilerin toplanacağı ana mail 🎯
      reply_to: email, // Azime Hanım mail içinden "Cevapla" derse direkt müşteriye yazar
      subject: `New Appointment Request: ${service} - ${name}`,
      html: `
        <div style="font-family: sans-serif; padding: 30px; border: 1px solid #C0AE92; border-radius: 12px; max-width: 600px; color: #333;">
          <h2 style="color: #B50004; border-bottom: 2px solid #F5F5F5; padding-bottom: 15px; margin-bottom: 20px;">
            New Appointment Request
          </h2>
          
          <div style="line-height: 1.8;">
            <p style="margin: 10px 0;"><strong>Customer Name:</strong> ${name}</p>
            <p style="margin: 10px 0;"><strong>Service Requested:</strong> ${service}</p>
            <p style="margin: 10px 0;"><strong>Preferred Date/Time:</strong> ${date}</p>
            <p style="margin: 10px 0;"><strong>Phone Number:</strong> ${phone}</p>
            <p style="margin: 10px 0;"><strong>Customer Email:</strong> ${email}</p>
            
            <div style="background-color: #F9F9F9; padding: 20px; border-radius: 8px; margin-top: 20px; border-left: 4px solid #C0AE92;">
              <strong style="display: block; margin-bottom: 5px;">Customer Note:</strong>
              ${message || 'No additional notes provided.'}
            </div>
          </div>

          <p style="font-size: 12px; color: #999; margin-top: 40px; text-align: center; border-top: 1px solid #EEE; padding-top: 20px;">
            This email was automatically generated by azimebeauty.com
          </p>
        </div>
      `,
    });

    // Müşteriye giden otomatik onay mailini senin isteğin üzerine tamamen kaldırdım.
    // Artık sadece Azime Hanım mail alacak.

    return NextResponse.json({ success: true }, { status: 200 });
  } catch (error) {
    console.error("Resend Error Detail:", error);
    return NextResponse.json({ error: "Email failed", detail: error.message }, { status: 500 });
  }
}